repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
    - id: ruff
      args: [ --fix]
    - id: ruff-format
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: poetry run pytest
        language: system
        args: [./tests]
        pass_filenames: false
        